package com.solid.carry1stshop.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF6B5C4D)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFF4DFCD)
val light_onPrimaryContainer = Color(0xFF241A0E)
val light_secondary = Color(0xFF635D59)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFEAE1DB)
val light_onSecondaryContainer = Color(0xFF1F1B17)
val light_tertiary = Color(0xFF5E5F58)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFE3E3DA)
val light_onTertiaryContainer = Color(0xFF1B1C17)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFF5F0EE)
val light_onBackground = Color(0xFF1D1B1A)
val light_surface = Color(0xFFFFFBFF)
val light_onSurface = Color(0xFF1D1B1A)
val light_surfaceVariant = Color(0xFFE7E1DE)
val light_onSurfaceVariant = Color(0xFF494644)
val light_outline = Color(0xFF7A7674)

val dark_primary = Color(0xFFD7C3B1)
val dark_onPrimary = Color(0xFF3A2E22)
val dark_primaryContainer = Color(0xFF524437)
val dark_onPrimaryContainer = Color(0xFFF4DFCD)
val dark_secondary = Color(0xFFCDC5BF)
val dark_onSecondary = Color(0xFF34302C)
val dark_secondaryContainer = Color(0xFF4B4642)
val dark_onSecondaryContainer = Color(0xFFEAE1DB)
val dark_tertiary = Color(0xFFC7C7BE)
val dark_onTertiary = Color(0xFF30312B)
val dark_tertiaryContainer = Color(0xFF464741)
val dark_onTertiaryContainer = Color(0xFFE3E3DA)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFB4AB)
val dark_background = Color(0xFF32302F)
val dark_onBackground = Color(0xFFE6E1E0)
val dark_surface = Color(0xFF1D1B1A)
val dark_onSurface = Color(0xFFE6E1E0)
val dark_surfaceVariant = Color(0xFF494644)
val dark_onSurfaceVariant = Color(0xFFE6E1E0)
val dark_outline = Color(0xFF94908D)